// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ddwNfuV1d3sS7wxTc5aLdh
// Component: _iYdZIivYdSy

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import ListItem from "../../ListItem"; // plasmic-import: 1QrNyfW0H0c7/component

import { ModeValue, useMode } from "../global/PlasmicGlobalVariant__Mode"; // plasmic-import: 4o07efrW3bsm/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_global_css from "../global/plasmic_global.module.css"; // plasmic-import: 8hqEu73KETDHFVi1kzitzB/projectcss
import plasmic_semantic_css from "../semantic/plasmic_semantic.module.css"; // plasmic-import: b1udyYxbVnA5YsUcRMaXei/projectcss
import plasmic_components_css from "../components/plasmic_components.module.css"; // plasmic-import: 5ccFCnH7of5M9MPpSs86Uj/projectcss
import projectcss from "./plasmic_patterns.module.css"; // plasmic-import: ddwNfuV1d3sS7wxTc5aLdh/projectcss
import sty from "./PlasmicList.module.css"; // plasmic-import: _iYdZIivYdSy/css

import ChecksvgIcon from "../components/icons/PlasmicIcon__Checksvg"; // plasmic-import: Gl9W2RPSIc13/icon

createPlasmicElementProxy;

export type PlasmicList__VariantMembers = {
  multiItems: "_2" | "_3" | "_4" | "_5";
};
export type PlasmicList__VariantsArgs = {
  multiItems?: SingleChoiceArg<"_2" | "_3" | "_4" | "_5">;
};
type VariantPropType = keyof PlasmicList__VariantsArgs;
export const PlasmicList__VariantProps = new Array<VariantPropType>(
  "multiItems"
);

export type PlasmicList__ArgsType = {
  listItem6?: React.ReactNode;
  listItem7?: React.ReactNode;
  listItem8?: React.ReactNode;
  listItem9?: React.ReactNode;
  listItem10?: React.ReactNode;
};
type ArgPropType = keyof PlasmicList__ArgsType;
export const PlasmicList__ArgProps = new Array<ArgPropType>(
  "listItem6",
  "listItem7",
  "listItem8",
  "listItem9",
  "listItem10"
);

export type PlasmicList__OverridesType = {
  root?: Flex__<"div">;
};

export interface DefaultListProps {
  listItem6?: React.ReactNode;
  listItem7?: React.ReactNode;
  listItem8?: React.ReactNode;
  listItem9?: React.ReactNode;
  listItem10?: React.ReactNode;
  multiItems?: SingleChoiceArg<"_2" | "_3" | "_4" | "_5">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicList__RenderFunc(props: {
  variants: PlasmicList__VariantsArgs;
  args: PlasmicList__ArgsType;
  overrides: PlasmicList__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "multiItems",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.multiItems
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    mode: useMode()
  });

  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_global_css.plasmic_tokens,
        plasmic_semantic_css.plasmic_tokens,
        plasmic_components_css.plasmic_tokens,
        sty.root,
        {
          [plasmic_global_css.global_mode_dark]: hasVariant(
            globalVariants,
            "mode",
            "dark"
          ),
          [sty.rootmultiItems__2]: hasVariant($state, "multiItems", "_2"),
          [sty.rootmultiItems__3]: hasVariant($state, "multiItems", "_3"),
          [sty.rootmultiItems__4]: hasVariant($state, "multiItems", "_4"),
          [sty.rootmultiItems__5]: hasVariant($state, "multiItems", "_5")
        }
      )}
    >
      {renderPlasmicSlot({
        defaultContents: (
          <ListItem
            className={classNames("__wab_instance", sty.listItem__kqKRi)}
          />
        ),

        value: args.listItem6
      })}
      {(
        hasVariant($state, "multiItems", "_5")
          ? true
          : hasVariant($state, "multiItems", "_4")
          ? true
          : hasVariant($state, "multiItems", "_3")
          ? true
          : hasVariant($state, "multiItems", "_2")
          ? true
          : false
      )
        ? renderPlasmicSlot({
            defaultContents: (
              <ListItem
                className={classNames("__wab_instance", sty.listItem__mAd7)}
              />
            ),

            value: args.listItem7
          })
        : null}
      {(
        hasVariant($state, "multiItems", "_5")
          ? true
          : hasVariant($state, "multiItems", "_4")
          ? true
          : hasVariant($state, "multiItems", "_3")
          ? true
          : hasVariant($state, "multiItems", "_2")
          ? false
          : false
      )
        ? renderPlasmicSlot({
            defaultContents: (
              <ListItem
                className={classNames("__wab_instance", sty.listItem__wNm2Q)}
              />
            ),

            value: args.listItem8
          })
        : null}
      {(
        hasVariant($state, "multiItems", "_5")
          ? true
          : hasVariant($state, "multiItems", "_4")
          ? true
          : false
      )
        ? renderPlasmicSlot({
            defaultContents: (
              <ListItem
                className={classNames("__wab_instance", sty.listItem__d4HBx)}
              />
            ),

            value: args.listItem9
          })
        : null}
      {(hasVariant($state, "multiItems", "_5") ? true : false)
        ? renderPlasmicSlot({
            defaultContents: (
              <ListItem
                className={classNames("__wab_instance", sty.listItem__hmYHv)}
              />
            ),

            value: args.listItem10
          })
        : null}
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicList__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicList__VariantsArgs;
    args?: PlasmicList__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicList__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicList__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicList__ArgProps,
          internalVariantPropNames: PlasmicList__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicList__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicList";
  } else {
    func.displayName = `PlasmicList.${nodeName}`;
  }
  return func;
}

export const PlasmicList = Object.assign(
  // Top-level PlasmicList renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicList
    internalVariantProps: PlasmicList__VariantProps,
    internalArgProps: PlasmicList__ArgProps
  }
);

export default PlasmicList;
/* prettier-ignore-end */
